// Daily Collectible Themes - 120+ unique themes organized by season

import type { Season } from './seasons';
import { getCurrentSeason } from './seasons';
import type {
  DailyTheme,
  DailyThemeColors,
  ThemeCategory,
} from './dailyThemes.types';
import { HOLIDAYS } from './dailyThemes.types';

// Helper to create theme colors with sensible dark mode variants
function createColors(
  bgPrimary: string,
  bgSecondary: string,
  timerStart: string,
  timerMid: string,
  timerEnd: string,
  textPrimary: string,
  accent: string,
  gradientAngle: number = 135
): DailyThemeColors {
  return {
    backgroundPrimary: bgPrimary,
    backgroundSecondary: bgSecondary,
    backgroundGradient: `linear-gradient(${gradientAngle}deg, ${bgPrimary} 0%, ${bgSecondary} 100%)`,
    timerStart,
    timerMid,
    timerEnd,
    timerBackground: lighten(bgPrimary, 0.1),
    timerBackgroundDark: darken(bgPrimary, 0.7),
    timerInnerCircle: lighten(bgPrimary, 0.2),
    timerInnerCircleDark: darken(bgPrimary, 0.8),
    timerProgress: timerStart,
    timerProgressDark: timerMid,
    textPrimary,
    textPrimaryDark: lighten(textPrimary, 0.5),
    textSecondary: lighten(textPrimary, 0.2),
    textSecondaryDark: lighten(textPrimary, 0.3),
    accent,
    accentDark: lighten(accent, 0.2),
  };
}

// Simple color manipulation helpers
function lighten(hex: string, amount: number): string {
  const num = parseInt(hex.slice(1), 16);
  const r = Math.min(255, Math.round(((num >> 16) & 0xff) + (255 - ((num >> 16) & 0xff)) * amount));
  const g = Math.min(
    255,
    Math.round(((num >> 8) & 0xff) + (255 - ((num >> 8) & 0xff)) * amount)
  );
  const b = Math.min(255, Math.round((num & 0xff) + (255 - (num & 0xff)) * amount));
  return `#${((r << 16) | (g << 8) | b).toString(16).padStart(6, '0')}`;
}

function darken(hex: string, amount: number): string {
  const num = parseInt(hex.slice(1), 16);
  const r = Math.max(0, Math.round(((num >> 16) & 0xff) * (1 - amount)));
  const g = Math.max(0, Math.round(((num >> 8) & 0xff) * (1 - amount)));
  const b = Math.max(0, Math.round((num & 0xff) * (1 - amount)));
  return `#${((r << 16) | (g << 8) | b).toString(16).padStart(6, '0')}`;
}

// ============================================================================
// SPRING THEMES (30 themes)
// ============================================================================

const SPRING_THEMES: DailyTheme[] = [
  {
    id: 'spring-day-1',
    name: 'Cherry Blossom Dreams',
    season: 'spring',
    dayNumber: 1,
    colors: createColors('#FFF0F5', '#FFE4EC', '#FFB7C5', '#FF91A4', '#FF6B8A', '#8B4557', '#FF69B4'),
    backgroundEffect: 'petals',
    decorativeElements: ['flowers'],
    categories: ['light', 'nature', 'whimsical'],
    description: 'Soft pink petals dancing in the breeze',
  },
  {
    id: 'spring-day-2',
    name: 'Morning Dew',
    season: 'spring',
    dayNumber: 2,
    colors: createColors('#E8F5E9', '#C8E6C9', '#81C784', '#66BB6A', '#4CAF50', '#2E7D32', '#69F0AE'),
    backgroundEffect: 'sparkles',
    decorativeElements: ['none'],
    categories: ['minimal', 'nature', 'light'],
    description: 'Fresh droplets glistening at dawn',
  },
  {
    id: 'spring-day-3',
    name: 'Tulip Garden',
    season: 'spring',
    dayNumber: 3,
    colors: createColors('#FFF3E0', '#FFE0B2', '#FF9800', '#FB8C00', '#F57C00', '#E65100', '#FFAB40'),
    backgroundEffect: 'none',
    decorativeElements: ['flowers'],
    categories: ['vibrant', 'nature'],
    description: 'A burst of color in the garden',
  },
  {
    id: 'spring-day-4',
    name: 'Lavender Fields',
    season: 'spring',
    dayNumber: 4,
    colors: createColors('#F3E5F5', '#E1BEE7', '#BA68C8', '#AB47BC', '#9C27B0', '#6A1B9A', '#EA80FC'),
    backgroundEffect: 'dust',
    decorativeElements: ['butterflies'],
    categories: ['cozy', 'nature', 'whimsical'],
    description: 'Purple waves stretching to the horizon',
  },
  {
    id: 'spring-day-5',
    name: 'Rainbow After Rain',
    season: 'spring',
    dayNumber: 5,
    colors: createColors('#E3F2FD', '#BBDEFB', '#64B5F6', '#42A5F5', '#2196F3', '#1565C0', '#448AFF'),
    backgroundEffect: 'sparkles',
    decorativeElements: ['clouds'],
    categories: ['whimsical', 'vibrant', 'light'],
    description: 'Colors emerging from the clouds',
  },
  {
    id: 'spring-day-6',
    name: 'Butterfly Meadow',
    season: 'spring',
    dayNumber: 6,
    colors: createColors('#FFFDE7', '#FFF9C4', '#FFEE58', '#FFEB3B', '#FDD835', '#F9A825', '#FFD740'),
    backgroundEffect: 'glitter',
    decorativeElements: ['butterflies', 'flowers'],
    categories: ['whimsical', 'vibrant', 'nature'],
    description: 'Fluttering wings in golden light',
  },
  {
    id: 'spring-day-7',
    name: 'Mint Fresh',
    season: 'spring',
    dayNumber: 7,
    colors: createColors('#E0F2F1', '#B2DFDB', '#4DB6AC', '#26A69A', '#009688', '#00695C', '#64FFDA'),
    backgroundEffect: 'none',
    decorativeElements: ['none'],
    categories: ['minimal', 'light'],
    description: 'Cool and refreshing like spring water',
  },
  {
    id: 'spring-day-8',
    name: 'Peach Sunrise',
    season: 'spring',
    dayNumber: 8,
    colors: createColors('#FBE9E7', '#FFCCBC', '#FF8A65', '#FF7043', '#FF5722', '#E64A19', '#FF6E40'),
    backgroundEffect: 'dust',
    decorativeElements: ['birds'],
    categories: ['cozy', 'light', 'nature'],
    description: 'Warm morning glow over the hills',
  },
  {
    id: 'spring-day-9',
    name: 'Fern Gully',
    season: 'spring',
    dayNumber: 9,
    colors: createColors('#E8F5E9', '#A5D6A7', '#66BB6A', '#43A047', '#388E3C', '#1B5E20', '#00E676'),
    backgroundEffect: 'leaves',
    decorativeElements: ['trees'],
    categories: ['nature', 'cozy', 'dark'],
    description: 'Deep in the forest shade',
  },
  {
    id: 'spring-day-10',
    name: 'Wisteria Twilight',
    season: 'spring',
    dayNumber: 10,
    colors: createColors('#EDE7F6', '#D1C4E9', '#9575CD', '#7E57C2', '#673AB7', '#4527A0', '#B388FF'),
    backgroundEffect: 'petals',
    decorativeElements: ['lanterns'],
    categories: ['whimsical', 'dark', 'nature'],
    description: 'Purple cascades at dusk',
  },
  {
    id: 'spring-day-11',
    name: 'Daisy Chain',
    season: 'spring',
    dayNumber: 11,
    colors: createColors('#FFFEF0', '#FFF8E1', '#FFECB3', '#FFD54F', '#FFCA28', '#FFA000', '#FFE57F'),
    backgroundEffect: 'none',
    decorativeElements: ['flowers'],
    categories: ['light', 'whimsical', 'minimal'],
    description: 'Simple joys linked together',
  },
  {
    id: 'spring-day-12',
    name: 'Rainy Day Cozy',
    season: 'spring',
    dayNumber: 12,
    colors: createColors('#ECEFF1', '#CFD8DC', '#90A4AE', '#78909C', '#607D8B', '#455A64', '#80CBC4'),
    backgroundEffect: 'rain',
    decorativeElements: ['clouds'],
    categories: ['cozy', 'minimal', 'dark'],
    description: 'Comfort in the gentle patter',
  },
  {
    id: 'spring-day-13',
    name: 'Lilac Mist',
    season: 'spring',
    dayNumber: 13,
    colors: createColors('#F8F4FC', '#E8DEF8', '#C9B6E4', '#A78BCA', '#8561AF', '#643A94', '#CE93D8'),
    backgroundEffect: 'fog',
    decorativeElements: ['flowers'],
    categories: ['cozy', 'whimsical', 'light'],
    description: 'Soft purple veils at dawn',
  },
  {
    id: 'spring-day-14',
    name: 'Sakura Night',
    season: 'spring',
    dayNumber: 14,
    colors: createColors('#2D1F3D', '#4A2C5A', '#FF8FAB', '#FF6B8A', '#FF4778', '#1A0F23', '#FFB7C5'),
    backgroundEffect: 'petals',
    decorativeElements: ['lanterns', 'moons'],
    categories: ['dark', 'whimsical', 'festive'],
    description: 'Blossoms glowing under moonlight',
  },
  {
    id: 'spring-day-15',
    name: 'Honeybee Garden',
    season: 'spring',
    dayNumber: 15,
    colors: createColors('#FFF8E1', '#FFECB3', '#FFD54F', '#FFC107', '#FFB300', '#FF8F00', '#FFE082'),
    backgroundEffect: 'dust',
    decorativeElements: ['flowers'],
    categories: ['vibrant', 'nature', 'cozy'],
    description: 'Busy buzzing among blooms',
  },
  {
    id: 'spring-day-16',
    name: 'Fresh Grass',
    season: 'spring',
    dayNumber: 16,
    colors: createColors('#F1F8E9', '#DCEDC8', '#AED581', '#9CCC65', '#8BC34A', '#689F38', '#CCFF90'),
    backgroundEffect: 'none',
    decorativeElements: ['none'],
    categories: ['minimal', 'nature', 'light'],
    description: 'New growth underfoot',
  },
  {
    id: 'spring-day-17',
    name: 'Spring Storm',
    season: 'spring',
    dayNumber: 17,
    colors: createColors('#263238', '#37474F', '#546E7A', '#78909C', '#90A4AE', '#B0BEC5', '#4DD0E1'),
    backgroundEffect: 'rain',
    decorativeElements: ['clouds'],
    categories: ['dark', 'nature'],
    description: 'Thunder rolling across the sky',
  },
  {
    id: 'spring-day-18',
    name: 'Pastel Dreams',
    season: 'spring',
    dayNumber: 18,
    colors: createColors('#FCE4EC', '#F8BBD0', '#F48FB1', '#F06292', '#EC407A', '#C2185B', '#FF80AB'),
    backgroundEffect: 'sparkles',
    decorativeElements: ['stars'],
    categories: ['whimsical', 'light'],
    description: 'Soft colors of imagination',
  },
  {
    id: 'spring-day-19',
    name: 'Forest Floor',
    season: 'spring',
    dayNumber: 19,
    colors: createColors('#EFEBE9', '#D7CCC8', '#A1887F', '#8D6E63', '#795548', '#5D4037', '#BCAAA4'),
    backgroundEffect: 'leaves',
    decorativeElements: ['mushrooms'],
    categories: ['nature', 'cozy', 'dark'],
    description: 'Hidden treasures among the roots',
  },
  {
    id: 'spring-day-20',
    name: 'Morning Glory',
    season: 'spring',
    dayNumber: 20,
    colors: createColors('#E8EAF6', '#C5CAE9', '#7986CB', '#5C6BC0', '#3F51B5', '#303F9F', '#8C9EFF'),
    backgroundEffect: 'dust',
    decorativeElements: ['flowers'],
    categories: ['light', 'nature'],
    description: 'Blue trumpets greeting the sun',
  },
  {
    id: 'spring-day-21',
    name: 'Coral Reef',
    season: 'spring',
    dayNumber: 21,
    colors: createColors('#FFF0ED', '#FFCDD2', '#EF9A9A', '#E57373', '#EF5350', '#C62828', '#FF8A80'),
    backgroundEffect: 'bubbles',
    decorativeElements: ['waves'],
    categories: ['vibrant', 'nature', 'whimsical'],
    description: 'Underwater spring awakening',
  },
  {
    id: 'spring-day-22',
    name: 'Gentle Breeze',
    season: 'spring',
    dayNumber: 22,
    colors: createColors('#E0F7FA', '#B2EBF2', '#80DEEA', '#4DD0E1', '#26C6DA', '#00ACC1', '#84FFFF'),
    backgroundEffect: 'dust',
    decorativeElements: ['clouds'],
    categories: ['minimal', 'light', 'nature'],
    description: 'Soft winds carrying warmth',
  },
  {
    id: 'spring-day-23',
    name: 'Rose Garden',
    season: 'spring',
    dayNumber: 23,
    colors: createColors('#FCE4EC', '#F8BBD0', '#F48FB1', '#EC407A', '#E91E63', '#AD1457', '#FF4081'),
    backgroundEffect: 'petals',
    decorativeElements: ['flowers'],
    categories: ['nature', 'vibrant', 'light'],
    description: 'Classic elegance in bloom',
  },
  {
    id: 'spring-day-24',
    name: 'Frog Pond',
    season: 'spring',
    dayNumber: 24,
    colors: createColors('#E0F2F1', '#B2DFDB', '#80CBC4', '#4DB6AC', '#26A69A', '#00796B', '#A7FFEB'),
    backgroundEffect: 'bubbles',
    decorativeElements: ['waves'],
    categories: ['nature', 'whimsical', 'cozy'],
    description: 'Lily pads and croaking songs',
  },
  {
    id: 'spring-day-25',
    name: 'Dandelion Wishes',
    season: 'spring',
    dayNumber: 25,
    colors: createColors('#FFFDE7', '#FFF9C4', '#FFF59D', '#FFEE58', '#FFEB3B', '#FBC02D', '#FFFF8D'),
    backgroundEffect: 'dust',
    decorativeElements: ['flowers'],
    categories: ['whimsical', 'light', 'nature'],
    description: 'Seeds carrying dreams away',
  },
  {
    id: 'spring-day-26',
    name: 'Twilight Iris',
    season: 'spring',
    dayNumber: 26,
    colors: createColors('#311B92', '#4527A0', '#5E35B1', '#7E57C2', '#9575CD', '#B39DDB', '#7C4DFF'),
    backgroundEffect: 'fireflies',
    decorativeElements: ['flowers'],
    categories: ['dark', 'nature', 'whimsical'],
    description: 'Purple blooms at golden hour',
  },
  {
    id: 'spring-day-27',
    name: 'Lemonade Stand',
    season: 'spring',
    dayNumber: 27,
    colors: createColors('#FFFDE7', '#FFF9C4', '#FFF176', '#FFEE58', '#FFEB3B', '#FDD835', '#FFFF00'),
    backgroundEffect: 'sparkles',
    decorativeElements: ['suns'],
    categories: ['vibrant', 'light', 'whimsical'],
    description: 'Sweet and tangy refreshment',
  },
  {
    id: 'spring-day-28',
    name: 'Moss Stone',
    season: 'spring',
    dayNumber: 28,
    colors: createColors('#E8F5E9', '#C8E6C9', '#A5D6A7', '#81C784', '#66BB6A', '#43A047', '#69F0AE'),
    backgroundEffect: 'none',
    decorativeElements: ['none'],
    categories: ['minimal', 'nature', 'cozy'],
    description: 'Ancient and peaceful',
  },
  {
    id: 'spring-day-29',
    name: 'Bluebell Wood',
    season: 'spring',
    dayNumber: 29,
    colors: createColors('#E3F2FD', '#BBDEFB', '#64B5F6', '#2196F3', '#1976D2', '#0D47A1', '#82B1FF'),
    backgroundEffect: 'fog',
    decorativeElements: ['trees', 'flowers'],
    categories: ['nature', 'whimsical', 'cozy'],
    description: 'A carpet of blue wonder',
  },
  {
    id: 'spring-day-30',
    name: 'First Butterfly',
    season: 'spring',
    dayNumber: 30,
    colors: createColors('#FFF8E1', '#FFECB3', '#FFE082', '#FFD54F', '#FFCA28', '#FFB300', '#FFD180'),
    backgroundEffect: 'glitter',
    decorativeElements: ['butterflies'],
    categories: ['whimsical', 'nature', 'festive'],
    description: 'Celebrating new beginnings',
  },
];

// ============================================================================
// SUMMER THEMES (30 themes)
// ============================================================================

const SUMMER_THEMES: DailyTheme[] = [
  {
    id: 'summer-day-1',
    name: 'Ocean Breeze',
    season: 'summer',
    dayNumber: 1,
    colors: createColors('#E0F7FA', '#B2EBF2', '#00BCD4', '#00ACC1', '#0097A7', '#006064', '#18FFFF'),
    backgroundEffect: 'bubbles',
    decorativeElements: ['waves'],
    categories: ['nature', 'light', 'vibrant'],
    description: 'Cool winds from the sea',
  },
  {
    id: 'summer-day-2',
    name: 'Tropical Paradise',
    season: 'summer',
    dayNumber: 2,
    colors: createColors('#E8F5E9', '#C8E6C9', '#4CAF50', '#43A047', '#388E3C', '#1B5E20', '#00E676'),
    backgroundEffect: 'leaves',
    decorativeElements: ['trees', 'birds'],
    categories: ['nature', 'vibrant'],
    description: 'Lush jungle vibes',
  },
  {
    id: 'summer-day-3',
    name: 'Sunset Beach',
    season: 'summer',
    dayNumber: 3,
    colors: createColors('#FFF3E0', '#FFE0B2', '#FF9800', '#FB8C00', '#F57C00', '#E65100', '#FFAB40'),
    backgroundEffect: 'sparkles',
    decorativeElements: ['suns', 'waves'],
    categories: ['cozy', 'nature', 'vibrant'],
    description: 'Golden hour by the shore',
  },
  {
    id: 'summer-day-4',
    name: 'Watermelon Sugar',
    season: 'summer',
    dayNumber: 4,
    colors: createColors('#FFEBEE', '#FFCDD2', '#EF5350', '#E53935', '#D32F2F', '#B71C1C', '#FF8A80'),
    backgroundEffect: 'none',
    decorativeElements: ['none'],
    categories: ['vibrant', 'light', 'festive'],
    description: 'Sweet summer treat',
  },
  {
    id: 'summer-day-5',
    name: 'Firefly Night',
    season: 'summer',
    dayNumber: 5,
    colors: createColors('#1A237E', '#283593', '#3F51B5', '#3949AB', '#303F9F', '#1A237E', '#FFEB3B'),
    backgroundEffect: 'fireflies',
    decorativeElements: ['moons', 'stars'],
    categories: ['dark', 'whimsical', 'nature'],
    description: 'Magical lights in the darkness',
  },
  {
    id: 'summer-day-6',
    name: 'Coral Sunrise',
    season: 'summer',
    dayNumber: 6,
    colors: createColors('#FBE9E7', '#FFCCBC', '#FF7043', '#FF5722', '#F4511E', '#E64A19', '#FF6E40'),
    backgroundEffect: 'dust',
    decorativeElements: ['suns', 'clouds'],
    categories: ['vibrant', 'light', 'nature'],
    description: 'A new day painted in coral',
  },
  {
    id: 'summer-day-7',
    name: 'Lemon Zest',
    season: 'summer',
    dayNumber: 7,
    colors: createColors('#FFFDE7', '#FFF9C4', '#FFEE58', '#FFEB3B', '#FDD835', '#F9A825', '#FFFF00'),
    backgroundEffect: 'sparkles',
    decorativeElements: ['none'],
    categories: ['vibrant', 'light', 'minimal'],
    description: 'Bright and citrusy energy',
  },
  {
    id: 'summer-day-8',
    name: 'Deep Sea',
    season: 'summer',
    dayNumber: 8,
    colors: createColors('#0D47A1', '#1565C0', '#1976D2', '#1E88E5', '#2196F3', '#42A5F5', '#82B1FF'),
    backgroundEffect: 'bubbles',
    decorativeElements: ['waves'],
    categories: ['dark', 'nature'],
    description: 'Mysteries of the abyss',
  },
  {
    id: 'summer-day-9',
    name: 'Cotton Candy Skies',
    season: 'summer',
    dayNumber: 9,
    colors: createColors('#FCE4EC', '#F8BBD0', '#F48FB1', '#F06292', '#EC407A', '#E91E63', '#FF80AB'),
    backgroundEffect: 'sparkles',
    decorativeElements: ['clouds'],
    categories: ['whimsical', 'light', 'festive'],
    description: 'Pink and blue swirls',
  },
  {
    id: 'summer-day-10',
    name: 'Mango Tango',
    season: 'summer',
    dayNumber: 10,
    colors: createColors('#FFF8E1', '#FFECB3', '#FFD54F', '#FFC107', '#FFB300', '#FF8F00', '#FFAB00'),
    backgroundEffect: 'none',
    decorativeElements: ['none'],
    categories: ['vibrant', 'light'],
    description: 'Tropical fruit dance',
  },
  {
    id: 'summer-day-11',
    name: 'Stargazer',
    season: 'summer',
    dayNumber: 11,
    colors: createColors('#0D0D2B', '#1A1A4E', '#2E2E7E', '#4A4AA8', '#6666CC', '#8888EE', '#AACCFF'),
    backgroundEffect: 'stars',
    decorativeElements: ['moons', 'stars'],
    categories: ['dark', 'whimsical'],
    description: 'Warm nights under constellations',
  },
  {
    id: 'summer-day-12',
    name: 'Palm Grove',
    season: 'summer',
    dayNumber: 12,
    colors: createColors('#E8F5E9', '#C8E6C9', '#81C784', '#66BB6A', '#4CAF50', '#388E3C', '#00E676'),
    backgroundEffect: 'leaves',
    decorativeElements: ['trees'],
    categories: ['nature', 'cozy'],
    description: 'Shade from swaying palms',
  },
  {
    id: 'summer-day-13',
    name: 'Beach Bonfire',
    season: 'summer',
    dayNumber: 13,
    colors: createColors('#3E2723', '#4E342E', '#6D4C41', '#FF6F00', '#FF8F00', '#FFA000', '#FFD54F'),
    backgroundEffect: 'sparkles',
    decorativeElements: ['moons'],
    categories: ['cozy', 'dark', 'festive'],
    description: 'Stories around the flames',
  },
  {
    id: 'summer-day-14',
    name: 'Ice Cream Swirl',
    season: 'summer',
    dayNumber: 14,
    colors: createColors('#FFF8F0', '#FFE4D4', '#FFB6B9', '#FAE3D9', '#BBDED6', '#8AC6D1', '#FFB6B9'),
    backgroundEffect: 'sparkles',
    decorativeElements: ['none'],
    categories: ['whimsical', 'light', 'festive'],
    description: 'Sweet summer indulgence',
  },
  {
    id: 'summer-day-15',
    name: 'Lagoon',
    season: 'summer',
    dayNumber: 15,
    colors: createColors('#E0F2F1', '#B2DFDB', '#4DB6AC', '#26A69A', '#009688', '#00796B', '#64FFDA'),
    backgroundEffect: 'bubbles',
    decorativeElements: ['waves'],
    categories: ['nature', 'light', 'cozy'],
    description: 'Crystal clear waters',
  },
  {
    id: 'summer-day-16',
    name: 'Hibiscus',
    season: 'summer',
    dayNumber: 16,
    colors: createColors('#FCE4EC', '#F8BBD0', '#E91E63', '#D81B60', '#C2185B', '#AD1457', '#FF4081'),
    backgroundEffect: 'petals',
    decorativeElements: ['flowers'],
    categories: ['vibrant', 'nature'],
    description: 'Exotic blooms in the sun',
  },
  {
    id: 'summer-day-17',
    name: 'Thunderhead',
    season: 'summer',
    dayNumber: 17,
    colors: createColors('#263238', '#37474F', '#455A64', '#546E7A', '#607D8B', '#78909C', '#E1F5FE'),
    backgroundEffect: 'rain',
    decorativeElements: ['clouds'],
    categories: ['dark', 'nature'],
    description: 'Summer storm brewing',
  },
  {
    id: 'summer-day-18',
    name: 'Papaya',
    season: 'summer',
    dayNumber: 18,
    colors: createColors('#FFF3E0', '#FFE0B2', '#FFCC80', '#FFB74D', '#FFA726', '#FB8C00', '#FFAB40'),
    backgroundEffect: 'none',
    decorativeElements: ['none'],
    categories: ['vibrant', 'minimal', 'light'],
    description: 'Sweet and tropical',
  },
  {
    id: 'summer-day-19',
    name: 'Midnight Swim',
    season: 'summer',
    dayNumber: 19,
    colors: createColors('#0A192F', '#172A45', '#303C55', '#0077B6', '#00B4D8', '#90E0EF', '#CAF0F8'),
    backgroundEffect: 'bubbles',
    decorativeElements: ['moons', 'stars'],
    categories: ['dark', 'nature', 'whimsical'],
    description: 'Cool waters under stars',
  },
  {
    id: 'summer-day-20',
    name: 'Sunflower Field',
    season: 'summer',
    dayNumber: 20,
    colors: createColors('#FFFDE7', '#FFF9C4', '#FFD54F', '#FFC107', '#FFB300', '#8D6E63', '#FFE57F'),
    backgroundEffect: 'dust',
    decorativeElements: ['flowers', 'suns'],
    categories: ['nature', 'vibrant', 'cozy'],
    description: 'Golden faces following the sun',
  },
  {
    id: 'summer-day-21',
    name: 'Caribbean Blue',
    season: 'summer',
    dayNumber: 21,
    colors: createColors('#E0F7FA', '#B2EBF2', '#4DD0E1', '#26C6DA', '#00BCD4', '#0097A7', '#84FFFF'),
    backgroundEffect: 'sparkles',
    decorativeElements: ['waves'],
    categories: ['vibrant', 'nature', 'light'],
    description: 'Island paradise waters',
  },
  {
    id: 'summer-day-22',
    name: 'Pineapple Express',
    season: 'summer',
    dayNumber: 22,
    colors: createColors('#FFFDE7', '#FFF9C4', '#FFD54F', '#388E3C', '#FFC107', '#8BC34A', '#FFFF00'),
    backgroundEffect: 'none',
    decorativeElements: ['none'],
    categories: ['vibrant', 'whimsical'],
    description: 'Tropical and spiky sweet',
  },
  {
    id: 'summer-day-23',
    name: 'Aurora Summer',
    season: 'summer',
    dayNumber: 23,
    colors: createColors('#1A237E', '#311B92', '#4A148C', '#6A1B9A', '#7B1FA2', '#8E24AA', '#E040FB'),
    backgroundEffect: 'aurora',
    decorativeElements: ['stars'],
    categories: ['dark', 'whimsical', 'nature'],
    description: 'Northern lights in warm nights',
  },
  {
    id: 'summer-day-24',
    name: 'Coconut',
    season: 'summer',
    dayNumber: 24,
    colors: createColors('#EFEBE9', '#D7CCC8', '#BCAAA4', '#A1887F', '#8D6E63', '#6D4C41', '#FFFFFF'),
    backgroundEffect: 'none',
    decorativeElements: ['trees'],
    categories: ['minimal', 'nature', 'cozy'],
    description: 'Simple tropical comfort',
  },
  {
    id: 'summer-day-25',
    name: 'Carnival Night',
    season: 'summer',
    dayNumber: 25,
    colors: createColors('#1A1A2E', '#16213E', '#E94560', '#FFD700', '#FF6B6B', '#4ECDC4', '#FF6B6B'),
    backgroundEffect: 'confetti',
    decorativeElements: ['fireworks', 'lanterns'],
    categories: ['festive', 'dark', 'vibrant'],
    description: 'Festival lights and music',
  },
  {
    id: 'summer-day-26',
    name: 'Kiwi Fresh',
    season: 'summer',
    dayNumber: 26,
    colors: createColors('#E8F5E9', '#C8E6C9', '#8BC34A', '#7CB342', '#689F38', '#558B2F', '#CCFF90'),
    backgroundEffect: 'none',
    decorativeElements: ['none'],
    categories: ['vibrant', 'light', 'minimal'],
    description: 'Green and tangy refreshment',
  },
  {
    id: 'summer-day-27',
    name: 'Sandcastle',
    season: 'summer',
    dayNumber: 27,
    colors: createColors('#FFF8E1', '#FFECB3', '#FFE082', '#FFD54F', '#D7CCC8', '#BCAAA4', '#FFE57F'),
    backgroundEffect: 'dust',
    decorativeElements: ['waves'],
    categories: ['cozy', 'whimsical', 'nature'],
    description: 'Building dreams on the shore',
  },
  {
    id: 'summer-day-28',
    name: 'Raspberry',
    season: 'summer',
    dayNumber: 28,
    colors: createColors('#FCE4EC', '#F8BBD0', '#EC407A', '#E91E63', '#D81B60', '#C2185B', '#FF4081'),
    backgroundEffect: 'sparkles',
    decorativeElements: ['none'],
    categories: ['vibrant', 'light'],
    description: 'Sweet and tart delight',
  },
  {
    id: 'summer-day-29',
    name: 'Lightning Bug',
    season: 'summer',
    dayNumber: 29,
    colors: createColors('#212121', '#424242', '#616161', '#CDDC39', '#C0CA33', '#AFB42B', '#EEFF41'),
    backgroundEffect: 'fireflies',
    decorativeElements: ['moons'],
    categories: ['dark', 'whimsical', 'nature'],
    description: 'Glowing summer magic',
  },
  {
    id: 'summer-day-30',
    name: 'Endless Horizon',
    season: 'summer',
    dayNumber: 30,
    colors: createColors('#87CEEB', '#B0E0E6', '#FFD700', '#FFA500', '#FF8C00', '#FF7F50', '#87CEEB'),
    backgroundEffect: 'dust',
    decorativeElements: ['suns', 'clouds'],
    categories: ['nature', 'light', 'cozy'],
    description: 'Where sky meets sea',
  },
];

// ============================================================================
// AUTUMN THEMES (30 themes)
// ============================================================================

const AUTUMN_THEMES: DailyTheme[] = [
  {
    id: 'autumn-day-1',
    name: 'Ember Twilight',
    season: 'autumn',
    dayNumber: 1,
    colors: createColors('#BF360C', '#D84315', '#E64A19', '#FF5722', '#FF7043', '#FF8A65', '#FF6E40'),
    backgroundEffect: 'leaves',
    decorativeElements: ['trees'],
    categories: ['cozy', 'nature', 'dark'],
    description: 'Fiery leaves at dusk',
  },
  {
    id: 'autumn-day-2',
    name: 'Pumpkin Spice',
    season: 'autumn',
    dayNumber: 2,
    colors: createColors('#FF6F00', '#FF8F00', '#FFA000', '#FFB300', '#FFC107', '#FFD54F', '#FFAB40'),
    backgroundEffect: 'dust',
    decorativeElements: ['pumpkins'],
    categories: ['cozy', 'festive', 'vibrant'],
    description: 'Warm and spicy comfort',
  },
  {
    id: 'autumn-day-3',
    name: 'Harvest Moon',
    season: 'autumn',
    dayNumber: 3,
    colors: createColors('#1A1A2E', '#2D2D44', '#FFB347', '#FFCC5C', '#FFD700', '#E6BE8A', '#FFE4B5'),
    backgroundEffect: 'stars',
    decorativeElements: ['moons', 'stars'],
    categories: ['dark', 'nature', 'whimsical'],
    description: 'Golden orb rising',
  },
  {
    id: 'autumn-day-4',
    name: 'Cranberry',
    season: 'autumn',
    dayNumber: 4,
    colors: createColors('#880E4F', '#AD1457', '#C2185B', '#D81B60', '#E91E63', '#F06292', '#F48FB1'),
    backgroundEffect: 'none',
    decorativeElements: ['none'],
    categories: ['vibrant', 'dark'],
    description: 'Deep berry richness',
  },
  {
    id: 'autumn-day-5',
    name: 'Misty Morning',
    season: 'autumn',
    dayNumber: 5,
    colors: createColors('#ECEFF1', '#CFD8DC', '#B0BEC5', '#90A4AE', '#78909C', '#607D8B', '#B0BEC5'),
    backgroundEffect: 'fog',
    decorativeElements: ['trees'],
    categories: ['minimal', 'nature', 'cozy'],
    description: 'Quiet gray beginnings',
  },
  {
    id: 'autumn-day-6',
    name: 'Apple Orchard',
    season: 'autumn',
    dayNumber: 6,
    colors: createColors('#FFEBEE', '#FFCDD2', '#EF5350', '#E53935', '#D32F2F', '#8BC34A', '#FF8A80'),
    backgroundEffect: 'leaves',
    decorativeElements: ['trees'],
    categories: ['nature', 'cozy', 'festive'],
    description: 'Red apples ready to pick',
  },
  {
    id: 'autumn-day-7',
    name: 'Butterscotch',
    season: 'autumn',
    dayNumber: 7,
    colors: createColors('#FFF8E1', '#FFECB3', '#FFD54F', '#FFC107', '#FFB300', '#FF8F00', '#FFE082'),
    backgroundEffect: 'none',
    decorativeElements: ['none'],
    categories: ['cozy', 'light', 'minimal'],
    description: 'Sweet golden comfort',
  },
  {
    id: 'autumn-day-8',
    name: 'Bonfire Glow',
    season: 'autumn',
    dayNumber: 8,
    colors: createColors('#3E2723', '#4E342E', '#5D4037', '#FF6F00', '#FF8F00', '#FFA000', '#FFD54F'),
    backgroundEffect: 'sparkles',
    decorativeElements: ['moons'],
    categories: ['cozy', 'dark', 'festive'],
    description: 'Crackling warmth in darkness',
  },
  {
    id: 'autumn-day-9',
    name: 'Rustic Barn',
    season: 'autumn',
    dayNumber: 9,
    colors: createColors('#5D4037', '#6D4C41', '#795548', '#8D6E63', '#A1887F', '#BCAAA4', '#D7CCC8'),
    backgroundEffect: 'dust',
    decorativeElements: ['mountains'],
    categories: ['cozy', 'nature', 'dark'],
    description: 'Weathered wood and hay',
  },
  {
    id: 'autumn-day-10',
    name: 'Cinnamon Swirl',
    season: 'autumn',
    dayNumber: 10,
    colors: createColors('#8D6E63', '#A1887F', '#D2691E', '#CD853F', '#DEB887', '#F5DEB3', '#FAEBD7'),
    backgroundEffect: 'dust',
    decorativeElements: ['none'],
    categories: ['cozy', 'minimal'],
    description: 'Warm spice spiraling',
  },
  {
    id: 'autumn-day-11',
    name: 'Maple Fire',
    season: 'autumn',
    dayNumber: 11,
    colors: createColors('#D84315', '#E64A19', '#FF5722', '#FF7043', '#FF8A65', '#FFAB91', '#FFCCBC'),
    backgroundEffect: 'leaves',
    decorativeElements: ['trees'],
    categories: ['vibrant', 'nature'],
    description: 'Trees ablaze with color',
  },
  {
    id: 'autumn-day-12',
    name: 'Mushroom Forest',
    season: 'autumn',
    dayNumber: 12,
    colors: createColors('#4E342E', '#5D4037', '#6D4C41', '#8D6E63', '#A1887F', '#BCAAA4', '#FF7043'),
    backgroundEffect: 'fog',
    decorativeElements: ['mushrooms', 'trees'],
    categories: ['nature', 'whimsical', 'dark'],
    description: 'Hidden treasures in the shade',
  },
  {
    id: 'autumn-day-13',
    name: 'Hot Cocoa',
    season: 'autumn',
    dayNumber: 13,
    colors: createColors('#3E2723', '#4E342E', '#5D4037', '#6D4C41', '#795548', '#8D6E63', '#EFEBE9'),
    backgroundEffect: 'none',
    decorativeElements: ['none'],
    categories: ['cozy', 'dark', 'minimal'],
    description: 'Warm cup in cold hands',
  },
  {
    id: 'autumn-day-14',
    name: 'Golden Hour',
    season: 'autumn',
    dayNumber: 14,
    colors: createColors('#FFE082', '#FFD54F', '#FFC107', '#FFB300', '#FFA000', '#FF8F00', '#FF6F00'),
    backgroundEffect: 'dust',
    decorativeElements: ['suns'],
    categories: ['light', 'nature', 'cozy'],
    description: 'Perfect photography light',
  },
  {
    id: 'autumn-day-15',
    name: 'Raven Night',
    season: 'autumn',
    dayNumber: 15,
    colors: createColors('#1A1A1A', '#2D2D2D', '#3D3D3D', '#4D4D4D', '#6D6D6D', '#8D8D8D', '#7C4DFF'),
    backgroundEffect: 'fog',
    decorativeElements: ['moons', 'birds'],
    categories: ['dark', 'nature'],
    description: 'Mysterious darkness descending',
  },
  {
    id: 'autumn-day-16',
    name: 'Caramel Apple',
    season: 'autumn',
    dayNumber: 16,
    colors: createColors('#D2691E', '#CD853F', '#DEB887', '#F5DEB3', '#D32F2F', '#C62828', '#FF6E40'),
    backgroundEffect: 'none',
    decorativeElements: ['none'],
    categories: ['festive', 'cozy', 'vibrant'],
    description: 'Sweet autumn treat',
  },
  {
    id: 'autumn-day-17',
    name: 'Foggy Creek',
    season: 'autumn',
    dayNumber: 17,
    colors: createColors('#78909C', '#90A4AE', '#B0BEC5', '#CFD8DC', '#ECEFF1', '#F5F5F5', '#607D8B'),
    backgroundEffect: 'fog',
    decorativeElements: ['trees', 'waves'],
    categories: ['nature', 'cozy', 'minimal'],
    description: 'Water whispers in the mist',
  },
  {
    id: 'autumn-day-18',
    name: 'Acorn Gathering',
    season: 'autumn',
    dayNumber: 18,
    colors: createColors('#795548', '#8D6E63', '#A1887F', '#BCAAA4', '#D7CCC8', '#EFEBE9', '#6D4C41'),
    backgroundEffect: 'leaves',
    decorativeElements: ['trees'],
    categories: ['nature', 'cozy', 'whimsical'],
    description: 'Preparing for winter',
  },
  {
    id: 'autumn-day-19',
    name: 'Plum Dusk',
    season: 'autumn',
    dayNumber: 19,
    colors: createColors('#4A148C', '#6A1B9A', '#7B1FA2', '#8E24AA', '#9C27B0', '#AB47BC', '#CE93D8'),
    backgroundEffect: 'stars',
    decorativeElements: ['moons'],
    categories: ['dark', 'whimsical'],
    description: 'Purple shadows lengthening',
  },
  {
    id: 'autumn-day-20',
    name: 'Wheat Field',
    season: 'autumn',
    dayNumber: 20,
    colors: createColors('#F5DEB3', '#DEB887', '#D2B48C', '#C4A35A', '#B8860B', '#DAA520', '#F0E68C'),
    backgroundEffect: 'dust',
    decorativeElements: ['none'],
    categories: ['nature', 'light', 'cozy'],
    description: 'Golden waves swaying',
  },
  {
    id: 'autumn-day-21',
    name: 'Cabin Retreat',
    season: 'autumn',
    dayNumber: 21,
    colors: createColors('#5D4037', '#6D4C41', '#795548', '#8D6E63', '#A1887F', '#BCAAA4', '#FF8F00'),
    backgroundEffect: 'fog',
    decorativeElements: ['trees', 'mountains'],
    categories: ['cozy', 'nature', 'dark'],
    description: 'Hidden in the woods',
  },
  {
    id: 'autumn-day-22',
    name: 'Persimmon',
    season: 'autumn',
    dayNumber: 22,
    colors: createColors('#FF5722', '#FF7043', '#FF8A65', '#FFAB91', '#FFCCBC', '#FBE9E7', '#E64A19'),
    backgroundEffect: 'none',
    decorativeElements: ['trees'],
    categories: ['vibrant', 'nature'],
    description: 'Sweet orange treasure',
  },
  {
    id: 'autumn-day-23',
    name: 'Storm Watch',
    season: 'autumn',
    dayNumber: 23,
    colors: createColors('#263238', '#37474F', '#455A64', '#546E7A', '#607D8B', '#78909C', '#B0BEC5'),
    backgroundEffect: 'rain',
    decorativeElements: ['clouds'],
    categories: ['dark', 'nature'],
    description: 'Thunder on the horizon',
  },
  {
    id: 'autumn-day-24',
    name: 'Toasted Marshmallow',
    season: 'autumn',
    dayNumber: 24,
    colors: createColors('#FFF8E1', '#FFECB3', '#FFE082', '#8D6E63', '#A1887F', '#BCAAA4', '#FFD180'),
    backgroundEffect: 'sparkles',
    decorativeElements: ['none'],
    categories: ['cozy', 'light', 'festive'],
    description: 'Perfectly golden and gooey',
  },
  {
    id: 'autumn-day-25',
    name: 'Scarecrow',
    season: 'autumn',
    dayNumber: 25,
    colors: createColors('#FF8F00', '#FFA000', '#FFB300', '#8D6E63', '#6D4C41', '#5D4037', '#FFAB40'),
    backgroundEffect: 'leaves',
    decorativeElements: ['pumpkins'],
    categories: ['whimsical', 'festive', 'nature'],
    description: 'Guardian of the harvest',
  },
  {
    id: 'autumn-day-26',
    name: 'Deep Woods',
    season: 'autumn',
    dayNumber: 26,
    colors: createColors('#1B5E20', '#2E7D32', '#388E3C', '#43A047', '#4CAF50', '#66BB6A', '#81C784'),
    backgroundEffect: 'fog',
    decorativeElements: ['trees', 'mushrooms'],
    categories: ['nature', 'dark'],
    description: 'Ancient forest secrets',
  },
  {
    id: 'autumn-day-27',
    name: 'Candlelight',
    season: 'autumn',
    dayNumber: 27,
    colors: createColors('#3E2723', '#4E342E', '#FFE082', '#FFD54F', '#FFC107', '#FFB300', '#FFE57F'),
    backgroundEffect: 'sparkles',
    decorativeElements: ['candles'],
    categories: ['cozy', 'dark', 'minimal'],
    description: 'Flickering warm glow',
  },
  {
    id: 'autumn-day-28',
    name: 'Hayride',
    season: 'autumn',
    dayNumber: 28,
    colors: createColors('#F5DEB3', '#DEB887', '#D2B48C', '#CD853F', '#D2691E', '#8B4513', '#FFE4B5'),
    backgroundEffect: 'dust',
    decorativeElements: ['pumpkins'],
    categories: ['festive', 'cozy', 'nature'],
    description: 'Bumpy ride through fields',
  },
  {
    id: 'autumn-day-29',
    name: 'Frost Warning',
    season: 'autumn',
    dayNumber: 29,
    colors: createColors('#ECEFF1', '#CFD8DC', '#B0BEC5', '#90A4AE', '#78909C', '#607D8B', '#B2EBF2'),
    backgroundEffect: 'dust',
    decorativeElements: ['leaves'],
    categories: ['minimal', 'nature', 'light'],
    description: 'Winter is coming',
  },
  {
    id: 'autumn-day-30',
    name: 'Last Light',
    season: 'autumn',
    dayNumber: 30,
    colors: createColors('#FF6F00', '#E65100', '#BF360C', '#3E2723', '#263238', '#1A1A1A', '#FF9100'),
    backgroundEffect: 'leaves',
    decorativeElements: ['trees', 'moons'],
    categories: ['dark', 'nature', 'cozy'],
    description: 'Farewell to golden days',
  },
];

// ============================================================================
// WINTER THEMES (30 themes)
// ============================================================================

const WINTER_THEMES: DailyTheme[] = [
  {
    id: 'winter-day-1',
    name: 'Frosted Morning',
    season: 'winter',
    dayNumber: 1,
    colors: createColors('#E3F2FD', '#BBDEFB', '#90CAF9', '#64B5F6', '#42A5F5', '#2196F3', '#82B1FF'),
    backgroundEffect: 'snow',
    decorativeElements: ['snowmen'],
    categories: ['light', 'nature'],
    description: 'Ice crystals sparkling',
  },
  {
    id: 'winter-day-2',
    name: 'Cozy Fireplace',
    season: 'winter',
    dayNumber: 2,
    colors: createColors('#3E2723', '#4E342E', '#5D4037', '#FF6F00', '#FF8F00', '#FFA000', '#FFD54F'),
    backgroundEffect: 'sparkles',
    decorativeElements: ['candles'],
    categories: ['cozy', 'dark'],
    description: 'Warmth in the cold',
  },
  {
    id: 'winter-day-3',
    name: 'Arctic Dream',
    season: 'winter',
    dayNumber: 3,
    colors: createColors('#E0F7FA', '#B2EBF2', '#80DEEA', '#4DD0E1', '#26C6DA', '#00BCD4', '#84FFFF'),
    backgroundEffect: 'aurora',
    decorativeElements: ['stars'],
    categories: ['nature', 'whimsical', 'light'],
    description: 'Colors dancing in polar skies',
  },
  {
    id: 'winter-day-4',
    name: 'Evergreen',
    season: 'winter',
    dayNumber: 4,
    colors: createColors('#1B5E20', '#2E7D32', '#388E3C', '#43A047', '#4CAF50', '#66BB6A', '#A5D6A7'),
    backgroundEffect: 'snow',
    decorativeElements: ['trees'],
    categories: ['nature', 'dark', 'festive'],
    description: 'Green amid the white',
  },
  {
    id: 'winter-day-5',
    name: 'Snowfall Serenity',
    season: 'winter',
    dayNumber: 5,
    colors: createColors('#FAFAFA', '#F5F5F5', '#EEEEEE', '#E0E0E0', '#BDBDBD', '#9E9E9E', '#FFFFFF'),
    backgroundEffect: 'snow',
    decorativeElements: ['none'],
    categories: ['minimal', 'light'],
    description: 'Peaceful white silence',
  },
  {
    id: 'winter-day-6',
    name: 'Cranberry Velvet',
    season: 'winter',
    dayNumber: 6,
    colors: createColors('#880E4F', '#AD1457', '#C2185B', '#D81B60', '#E91E63', '#EC407A', '#F48FB1'),
    backgroundEffect: 'sparkles',
    decorativeElements: ['none'],
    categories: ['vibrant', 'dark', 'festive'],
    description: 'Rich holiday elegance',
  },
  {
    id: 'winter-day-7',
    name: 'Icicle Palace',
    season: 'winter',
    dayNumber: 7,
    colors: createColors('#E8EAF6', '#C5CAE9', '#9FA8DA', '#7986CB', '#5C6BC0', '#3F51B5', '#8C9EFF'),
    backgroundEffect: 'glitter',
    decorativeElements: ['crystals'],
    categories: ['whimsical', 'light'],
    description: 'Frozen crystal kingdom',
  },
  {
    id: 'winter-day-8',
    name: 'Midnight Blue',
    season: 'winter',
    dayNumber: 8,
    colors: createColors('#0D47A1', '#1565C0', '#1976D2', '#1E88E5', '#2196F3', '#42A5F5', '#64B5F6'),
    backgroundEffect: 'stars',
    decorativeElements: ['moons', 'stars'],
    categories: ['dark', 'nature'],
    description: 'Deep winter night',
  },
  {
    id: 'winter-day-9',
    name: 'Hot Toddy',
    season: 'winter',
    dayNumber: 9,
    colors: createColors('#FF8F00', '#FFA000', '#FFB300', '#FFC107', '#FFD54F', '#FFE082', '#FFF8E1'),
    backgroundEffect: 'sparkles',
    decorativeElements: ['none'],
    categories: ['cozy', 'light'],
    description: 'Warm drink by the window',
  },
  {
    id: 'winter-day-10',
    name: 'Silver Bells',
    season: 'winter',
    dayNumber: 10,
    colors: createColors('#ECEFF1', '#CFD8DC', '#B0BEC5', '#90A4AE', '#78909C', '#607D8B', '#B0BEC5'),
    backgroundEffect: 'glitter',
    decorativeElements: ['stars'],
    categories: ['festive', 'light', 'minimal'],
    description: 'Jingling in the cold',
  },
  {
    id: 'winter-day-11',
    name: 'Polar Night',
    season: 'winter',
    dayNumber: 11,
    colors: createColors('#0A1929', '#132F4C', '#1E3A5F', '#265D97', '#2196F3', '#4FC3F7', '#B3E5FC'),
    backgroundEffect: 'stars',
    decorativeElements: ['moons'],
    categories: ['dark', 'nature'],
    description: 'Endless darkness above',
  },
  {
    id: 'winter-day-12',
    name: 'Peppermint',
    season: 'winter',
    dayNumber: 12,
    colors: createColors('#FFEBEE', '#FFCDD2', '#EF9A9A', '#E57373', '#FFFFFF', '#EF5350', '#FF8A80'),
    backgroundEffect: 'sparkles',
    decorativeElements: ['none'],
    categories: ['festive', 'whimsical', 'light'],
    description: 'Red and white swirls',
  },
  {
    id: 'winter-day-13',
    name: 'Wool Blanket',
    season: 'winter',
    dayNumber: 13,
    colors: createColors('#EFEBE9', '#D7CCC8', '#BCAAA4', '#A1887F', '#8D6E63', '#6D4C41', '#D7CCC8'),
    backgroundEffect: 'none',
    decorativeElements: ['none'],
    categories: ['cozy', 'minimal'],
    description: 'Soft and warm wrapping',
  },
  {
    id: 'winter-day-14',
    name: 'Northern Star',
    season: 'winter',
    dayNumber: 14,
    colors: createColors('#1A1A2E', '#16213E', '#0F3460', '#E94560', '#FFD700', '#FFFFFF', '#FFE082'),
    backgroundEffect: 'stars',
    decorativeElements: ['stars'],
    categories: ['dark', 'whimsical', 'festive'],
    description: 'Guiding light in darkness',
  },
  {
    id: 'winter-day-15',
    name: 'Snowdrift',
    season: 'winter',
    dayNumber: 15,
    colors: createColors('#E3F2FD', '#BBDEFB', '#90CAF9', '#64B5F6', '#42A5F5', '#2196F3', '#FFFFFF'),
    backgroundEffect: 'snow',
    decorativeElements: ['snowmen'],
    categories: ['light', 'nature', 'whimsical'],
    description: 'Piled high and soft',
  },
  {
    id: 'winter-day-16',
    name: 'Mulled Wine',
    season: 'winter',
    dayNumber: 16,
    colors: createColors('#4A0E0E', '#6D1313', '#8B0000', '#A52A2A', '#B22222', '#CD5C5C', '#F08080'),
    backgroundEffect: 'sparkles',
    decorativeElements: ['none'],
    categories: ['cozy', 'dark', 'festive'],
    description: 'Spiced warmth in a cup',
  },
  {
    id: 'winter-day-17',
    name: 'Frost Fern',
    season: 'winter',
    dayNumber: 17,
    colors: createColors('#E8F5E9', '#C8E6C9', '#A5D6A7', '#81C784', '#66BB6A', '#4CAF50', '#B2DFDB'),
    backgroundEffect: 'glitter',
    decorativeElements: ['none'],
    categories: ['nature', 'light', 'whimsical'],
    description: 'Ice patterns on glass',
  },
  {
    id: 'winter-day-18',
    name: 'Ski Lodge',
    season: 'winter',
    dayNumber: 18,
    colors: createColors('#5D4037', '#6D4C41', '#795548', '#8D6E63', '#FF6F00', '#FF8F00', '#FFAB40'),
    backgroundEffect: 'snow',
    decorativeElements: ['trees', 'mountains'],
    categories: ['cozy', 'nature'],
    description: 'Mountain retreat comfort',
  },
  {
    id: 'winter-day-19',
    name: 'Ice Crystal',
    season: 'winter',
    dayNumber: 19,
    colors: createColors('#E0F7FA', '#B2EBF2', '#80DEEA', '#4DD0E1', '#26C6DA', '#00BCD4', '#FFFFFF'),
    backgroundEffect: 'glitter',
    decorativeElements: ['crystals'],
    categories: ['light', 'minimal', 'nature'],
    description: 'Perfect geometric beauty',
  },
  {
    id: 'winter-day-20',
    name: 'Holly Berry',
    season: 'winter',
    dayNumber: 20,
    colors: createColors('#1B5E20', '#2E7D32', '#388E3C', '#D32F2F', '#C62828', '#B71C1C', '#F44336'),
    backgroundEffect: 'sparkles',
    decorativeElements: ['none'],
    categories: ['festive', 'nature', 'vibrant'],
    description: 'Classic holiday colors',
  },
  {
    id: 'winter-day-21',
    name: 'Twilight Snow',
    season: 'winter',
    dayNumber: 21,
    colors: createColors('#311B92', '#4527A0', '#512DA8', '#5E35B1', '#673AB7', '#7E57C2', '#B388FF'),
    backgroundEffect: 'snow',
    decorativeElements: ['moons', 'stars'],
    categories: ['dark', 'whimsical'],
    description: 'Purple dusk over white',
  },
  {
    id: 'winter-day-22',
    name: 'Gingerbread',
    season: 'winter',
    dayNumber: 22,
    colors: createColors('#8B4513', '#A0522D', '#CD853F', '#DEB887', '#FFFFFF', '#F5DEB3', '#D2691E'),
    backgroundEffect: 'sparkles',
    decorativeElements: ['none'],
    categories: ['cozy', 'festive', 'whimsical'],
    description: 'Sweet spiced delight',
  },
  {
    id: 'winter-day-23',
    name: 'Blizzard',
    season: 'winter',
    dayNumber: 23,
    colors: createColors('#B0BEC5', '#90A4AE', '#78909C', '#607D8B', '#546E7A', '#455A64', '#ECEFF1'),
    backgroundEffect: 'snow',
    decorativeElements: ['clouds'],
    categories: ['nature', 'dark'],
    description: 'White-out conditions',
  },
  {
    id: 'winter-day-24',
    name: 'Candycane Lane',
    season: 'winter',
    dayNumber: 24,
    colors: createColors('#FFFFFF', '#FFCDD2', '#EF9A9A', '#E57373', '#EF5350', '#F44336', '#FF8A80'),
    backgroundEffect: 'glitter',
    decorativeElements: ['none'],
    categories: ['festive', 'whimsical', 'light'],
    description: 'Striped holiday joy',
  },
  {
    id: 'winter-day-25',
    name: 'Starlight',
    season: 'winter',
    dayNumber: 25,
    colors: createColors('#0D0D2B', '#1A1A4E', '#2E2E7E', '#FFD700', '#FFC107', '#FFEB3B', '#FFFFFF'),
    backgroundEffect: 'stars',
    decorativeElements: ['stars'],
    categories: ['dark', 'whimsical', 'festive'],
    description: 'Twinkling winter magic',
  },
  {
    id: 'winter-day-26',
    name: 'Frozen Lake',
    season: 'winter',
    dayNumber: 26,
    colors: createColors('#E3F2FD', '#BBDEFB', '#90CAF9', '#64B5F6', '#42A5F5', '#1E88E5', '#B3E5FC'),
    backgroundEffect: 'glitter',
    decorativeElements: ['trees'],
    categories: ['nature', 'light', 'minimal'],
    description: 'Smooth ice stretching',
  },
  {
    id: 'winter-day-27',
    name: 'Sugarplum',
    season: 'winter',
    dayNumber: 27,
    colors: createColors('#F3E5F5', '#E1BEE7', '#CE93D8', '#BA68C8', '#AB47BC', '#8E24AA', '#EA80FC'),
    backgroundEffect: 'sparkles',
    decorativeElements: ['stars'],
    categories: ['whimsical', 'festive', 'light'],
    description: 'Dancing in dreams',
  },
  {
    id: 'winter-day-28',
    name: 'Cabin Fever',
    season: 'winter',
    dayNumber: 28,
    colors: createColors('#5D4037', '#6D4C41', '#795548', '#8D6E63', '#A1887F', '#BCAAA4', '#FF8F00'),
    backgroundEffect: 'snow',
    decorativeElements: ['trees', 'candles'],
    categories: ['cozy', 'dark'],
    description: 'Snowed in but warm',
  },
  {
    id: 'winter-day-29',
    name: 'Glacier',
    season: 'winter',
    dayNumber: 29,
    colors: createColors('#E0F7FA', '#B2EBF2', '#80DEEA', '#4DD0E1', '#26C6DA', '#00ACC1', '#00838F'),
    backgroundEffect: 'glitter',
    decorativeElements: ['mountains'],
    categories: ['nature', 'minimal', 'light'],
    description: 'Ancient ice monument',
  },
  {
    id: 'winter-day-30',
    name: 'New Dawn',
    season: 'winter',
    dayNumber: 30,
    colors: createColors('#FFF3E0', '#FFE0B2', '#FFCC80', '#FFB74D', '#FFA726', '#FF9800', '#E3F2FD'),
    backgroundEffect: 'sparkles',
    decorativeElements: ['suns', 'stars'],
    categories: ['light', 'cozy', 'nature'],
    description: 'Light returning slowly',
  },
];

// ============================================================================
// SPECIAL HOLIDAY THEMES
// ============================================================================

export const SPECIAL_THEMES: DailyTheme[] = [
  {
    id: 'new-year',
    name: 'Midnight Sparkle',
    season: 'winter',
    dayNumber: 0,
    colors: createColors('#0D0D2B', '#1A1A4E', '#2E2E7E', '#FFD700', '#FFC107', '#FFEB3B', '#FFFFFF'),
    backgroundEffect: 'confetti',
    decorativeElements: ['fireworks', 'stars'],
    categories: ['festive', 'dark', 'vibrant'],
    description: 'Celebration of new beginnings',
    isSpecial: true,
    specialDate: { month: 1, day: 1 },
  },
  {
    id: 'valentine',
    name: 'Heartbeat',
    season: 'winter',
    dayNumber: 0,
    colors: createColors('#FCE4EC', '#F8BBD0', '#F48FB1', '#EC407A', '#E91E63', '#C2185B', '#FF4081'),
    backgroundEffect: 'hearts',
    decorativeElements: ['hearts'],
    categories: ['festive', 'whimsical', 'vibrant'],
    description: 'Love in the air',
    isSpecial: true,
    specialDate: { month: 2, day: 14 },
  },
  {
    id: 'easter',
    name: 'Spring Awakening',
    season: 'spring',
    dayNumber: 0,
    colors: createColors('#E8F5E9', '#C8E6C9', '#A5D6A7', '#FFE082', '#F48FB1', '#CE93D8', '#81C784'),
    backgroundEffect: 'petals',
    decorativeElements: ['eggs', 'flowers', 'butterflies'],
    categories: ['festive', 'whimsical', 'nature'],
    description: 'Renewal and rebirth',
    isSpecial: true,
    specialDate: { month: 4, day: 9 },
  },
  {
    id: 'summer-solstice',
    name: 'Endless Day',
    season: 'summer',
    dayNumber: 0,
    colors: createColors('#FFF8E1', '#FFECB3', '#FFD54F', '#FFC107', '#FFB300', '#FF8F00', '#FFFF00'),
    backgroundEffect: 'sparkles',
    decorativeElements: ['suns'],
    categories: ['festive', 'vibrant', 'nature'],
    description: 'Longest day celebration',
    isSpecial: true,
    specialDate: { month: 6, day: 21 },
  },
  {
    id: 'halloween',
    name: 'Spooky Night',
    season: 'autumn',
    dayNumber: 0,
    colors: createColors('#1A1A1A', '#2D2D2D', '#FF6F00', '#FF8F00', '#7B1FA2', '#6A1B9A', '#FF9100'),
    backgroundEffect: 'fog',
    decorativeElements: ['pumpkins', 'moons', 'candles'],
    categories: ['festive', 'dark', 'whimsical'],
    description: 'Spooky and mysterious',
    isSpecial: true,
    specialDate: { month: 10, day: 31 },
  },
  {
    id: 'winter-solstice',
    name: 'Longest Night',
    season: 'winter',
    dayNumber: 0,
    colors: createColors('#0D0D2B', '#1A1A4E', '#311B92', '#4527A0', '#512DA8', '#FFFFFF', '#7C4DFF'),
    backgroundEffect: 'aurora',
    decorativeElements: ['moons', 'stars', 'candles'],
    categories: ['dark', 'cozy', 'nature'],
    description: 'Celebrating darkness before light',
    isSpecial: true,
    specialDate: { month: 12, day: 21 },
  },
  {
    id: 'christmas',
    name: 'Silent Night',
    season: 'winter',
    dayNumber: 0,
    colors: createColors('#1B5E20', '#2E7D32', '#388E3C', '#D32F2F', '#C62828', '#FFD700', '#FFFFFF'),
    backgroundEffect: 'snow',
    decorativeElements: ['trees', 'stars', 'presents'],
    categories: ['festive', 'cozy', 'whimsical'],
    description: 'Peace and joy',
    isSpecial: true,
    specialDate: { month: 12, day: 25 },
  },
];

// ============================================================================
// COMBINED THEMES
// ============================================================================

export const DAILY_THEMES: DailyTheme[] = [
  ...SPRING_THEMES,
  ...SUMMER_THEMES,
  ...AUTUMN_THEMES,
  ...WINTER_THEMES,
];

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

/**
 * Get all themes including special holiday themes
 */
export function getAllThemes(): DailyTheme[] {
  return [...DAILY_THEMES, ...SPECIAL_THEMES];
}

/**
 * Get a theme by its ID
 */
export function getThemeById(id: string): DailyTheme | undefined {
  return getAllThemes().find((theme) => theme.id === id);
}

/**
 * Get all themes for a specific season (excluding special themes)
 */
export function getThemesForSeason(season: Season): DailyTheme[] {
  return DAILY_THEMES.filter((theme) => theme.season === season);
}

/**
 * Get themes by category
 */
export function getThemesByCategory(category: ThemeCategory): DailyTheme[] {
  return getAllThemes().filter((theme) => theme.categories.includes(category));
}

/**
 * Check if a year is a leap year
 */
export function isLeapYear(year: number): boolean {
  return (year % 4 === 0 && year % 100 !== 0) || year % 400 === 0;
}

/**
 * Get day of year (1-366)
 */
export function getDayOfYear(date: Date): number {
  const start = new Date(date.getFullYear(), 0, 0);
  const diff = date.getTime() - start.getTime();
  const oneDay = 1000 * 60 * 60 * 24;
  return Math.floor(diff / oneDay);
}

/**
 * Get holiday theme for a specific date (if exists)
 */
export function getHolidayTheme(month: number, day: number): DailyTheme | null {
  const holiday = HOLIDAYS.find((h) => h.month === month && h.day === day);
  if (!holiday) return null;
  return SPECIAL_THEMES.find((t) => t.id === holiday.themeId) || null;
}

/**
 * Get the theme for a specific date
 */
export function getThemeForDate(date: Date): DailyTheme {
  const month = date.getMonth() + 1; // 1-indexed
  const day = date.getDate();

  // Check for holiday theme first
  const holidayTheme = getHolidayTheme(month, day);
  if (holidayTheme) {
    return holidayTheme;
  }

  // Get the current season
  const season = getCurrentSeason(date);

  // Get themes for this season
  const seasonThemes = getThemesForSeason(season);

  // Use day of year to pick a theme (modulo to cycle through themes)
  const dayOfYear = getDayOfYear(date);

  // Map day of year to theme index (ensuring variety across the season)
  const themeIndex = (dayOfYear - 1) % seasonThemes.length;

  const theme = seasonThemes[themeIndex];
  if (!theme) {
    // Fallback to first theme of season (should never happen)
    return seasonThemes[0]!;
  }
  return theme;
}
